### ISSUE TITLE
Website Alpha / MVP

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#52]
Imo the below is going to be site's MVP (pre alpha):

- [x] Shows currently running alerts (All Alerts page & RTM) https://github.com/ps2alerts/website/issues/54 https://github.com/ps2alerts/website/issues/55
- [x] Shows past alerts and their results (All Alerts Page) https://github.com/ps2alerts/website/issues/54
- [x] Shows real time updates of the current alerts (RTM) #55 
- Shows the following stats on the Alerts page https://github.com/ps2alerts/website/issues/56
  - [x] Basic faction combat statistics (total deaths / kills / suicides / TKs / headshots)
  - [x] Not real time sortable leaderboard (making the killboard real time is potentially quite a lot of work) - recommend use of [DataTables](https://datatables.net/) for this 

All this created out of purely static API calls, no real time data just yet as we've not set up the API websocket server to facilitate this. Real time monitor will do an AJAX call to get the latest updates every 10 seconds or so.

This will also not have proper styling, just pure information.

We also need a design: #53

**Comment by microwavekonijn** [comment]
https://gist.github.com/microwavekonijn/86430dedb0bc30602908e04a80fced9e
https://gist.github.com/microwavekonijn/9edaeeca09d8950ddd04b91782a1e7b4
